# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-24 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_User',
        ),
    ]
