# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-24 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_user_no_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='no_login',
        ),
    ]
