# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-24 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_user_no_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_login',
            field=models.IntegerField(default=None, max_length=2, null=True),
        ),
    ]
